[package]
name = "stockin_api"
version = "0.1.0"
edition = "2018"
default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
axum = "0.2.0"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "sqlite", "offline", "chrono"] }
tokio = {version = "1", features = ["full"] }

[[bin]]
name = "main"
path = "src/bin/main.rs"

[[bin]]
name = "seed"
path = "src/bin/seed.rs"
