services:
  app:
    build:
      context: ./
      dockerfile: docker/dev/Dockerfile
    command: make start
    init: true
    environment:
      DATABASE_URL: mysql://root:pass@db:3306/dev
      TEST_DATABASE_URL: mysql://root:pass@db:3306/test
      DATABASE_HOST: db
      AUTH_TOKEN: debug
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace
      - cargo:/usr/local/cargo
      - target:/workspace/target

  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"

volumes:
  cargo:
  target:
