version: '3.9'

services:
  app:
    image: ${IMAGE_TAG}
    environment:
      DATABASE_URL: mysql://root:${DATABASE_PASSWORD}@db:3306/prod
      AUTH_TOKEN: ${AUTH_TOKEN}
    ports:
      - "36918:3000"
    depends_on:
      - db
    init: true

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: prod
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
