version: '3.9'

services:
  app:
    image: registry.gitlab.com/techno-tanoc/stockin_api:0.1.0
    build:
      context: ../
      dockerfile: docker/deploy/Dockerfile
    init: true
    environment:
      DATABASE_URL: mysql://root:pass@db:3306/dev
      AUTH_TOKEN: debug
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: dev
    ports:
      - "3306:3306"
