version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: docker/dev/Dockerfile
    command: sh -c "
      dockerize -timeout 30s -wait tcp://db:3306 &&
      make reset &&
      cargo watch -x run"
    init: true
    environment:
      DATABASE_URL: mysql://root:pass@db:3306/dev
      DATABASE_HOST: db
      AUTH_TOKEN: debug
    ports:
      - "3000:3000"
    volumes:
      - .:/work
      - target:/work/target
    depends_on:
      - db

  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: dev
    ports:
      - "3306:3306"

volumes:
  target:
