CREATE TABLE items(
  id          BIGINT PRIMARY KEY AUTO_INCREMENT,
  title       TEXT NOT NULL,
  url         TEXT NOT NULL,
  is_archived BOOLEAN NOT NULL DEFAULT 0,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
