// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: item_tag.sql

package queries

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const deleteItemTag = `-- name: DeleteItemTag :exec
DELETE FROM item_tags
WHERE id = $1
`

func (q *Queries) DeleteItemTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteItemTag, id)
	return err
}

const insertItemTag = `-- name: InsertItemTag :exec
INSERT INTO item_tags(id, item_id, tag_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertItemTagParams struct {
	ID        uuid.UUID
	ItemID    uuid.UUID
	TagID     uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertItemTag(ctx context.Context, arg InsertItemTagParams) error {
	_, err := q.db.ExecContext(ctx, insertItemTag,
		arg.ID,
		arg.ItemID,
		arg.TagID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
