// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package queries

import (
	"time"

	"github.com/gofrs/uuid"
)

type Item struct {
	ID        uuid.UUID
	Title     string
	Url       string
	Thumbnail string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ItemTag struct {
	ID        uuid.UUID
	ItemID    uuid.UUID
	TagID     uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Tag struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
