services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      DATABASE: "host=postgres port=5432 user=root password=pass dbname=dev sslmode=disable"
      TOKEN: debug
    platform: linux/x86_64
    ports:
      - "3000:3000"

  postgres:
    image: postgres:13.7
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    platform: linux/x86_64
