services:
  app:
    build: .
    command: sleep infinity
    environment:
      DATABASE: root:pass@(db)/dev?parseTime=true
      TOKEN: debug
    init: true
    platform: linux/x86_64
    volumes:
      - ..:/workspace

  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: pass
    platform: linux/x86_64
    ports:
      - "3306:3306"
