name: CD

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, rutile]
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: stockin_api
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./docker/release/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: false

      - name: Deploy
        env:
          IMAGE_TAG: ${{ steps.meta.outputs.tags }}
          DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          docker-compose -f docker/release/compose.yaml up -d db
          docker-compose -f docker/release/compose.yaml run --rm app make wait
          docker-compose -f docker/release/compose.yaml run --rm app make migrate
          docker-compose -f docker/release/compose.yaml up -d app
