name: CD

on:
  push:
    branches:
      - sqlc
    # tags:
    #   - v*

jobs:
  build_and_push:
    name: Build and Push
    runs-on: [self-hosted, rutile]
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login GitLab
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: techno-tanoC
          password: ${{ secrets.GITLAB_DEPLOY_API_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.gitlab.com/techno-tanoc/stockin_api
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./docker/release/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: false
